# Generated by Django 5.0.7 on 2024-08-06 05:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место выполнения')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('habit_is_pleasant', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
                ('number_of_executions', models.IntegerField(default=1, verbose_name='Периодичность (в днях) - от 1 до 7')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='Время на выполнение (в минутах)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публичности')),
                ('connection_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habits', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
