# Generated by Django 5.0.7 on 2024-08-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="number_of_executions",
            field=models.IntegerField(
                default=7, verbose_name="Периодичность (в днях) - от 1 до 7"
            ),
        ),
    ]
